### ISSUE TITLE
error: Android NDK: Module perf depends on undefined modules: z lzma dl

### ISSUE THREAD

**Issue by HongxiaoMa** [linzj/linux-tool-perf-android-arm#1]
my config ndk = android-ndk-r16b

error:

/android-ndk-r16b/build/core/build-binary.mk:693: Android NDK: Module perf depends on undefined modules: z lzma dl

**Comment by linzj** [comment]
I am not maintaining this project.
I am now building the perf from the linux source tree instead.
The building script is in https://github.com/linzj/myscripts/tree/master/buildscript
